### ISSUE TITLE
Cannot update to Shippo 2.0.0

### ISSUE THREAD

**Issue by musukvl** [goshippo/shippo-csharp-client#25]
Steps to reproduce:
In Visual Studio 2015 
1. Create Console application.
2. Install Shippo 1.5.7
3. Add code:
```
using Shippo;
namespace TestApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Shipment x = new Shipment();
        }
    }
}
```
4. Update  Shippo to 2.0.0.0
5. Rebuild.
6. see  following exception:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'Shippo' could not be found (are you missing a using directive or an assembly reference?)	TestApp	d:\dev\test\TestApp\TestApp\Program.cs	6	Active
```

**Comment by musukvl** [comment]
Looks like Shippo.2.0.0.nupkg broken

![image](https://cloud.githubusercontent.com/assets/3954761/25723018/09b20042-311f-11e7-9920-0fc29316f5cd.png)

**Comment by mootrichard** [comment]
Thanks for highlighting this, I ran into a similar issue in my local environment and will investigate this further with our team.

**Comment by NVentimiglia** [comment]
Installed 2.0, no dlls included in the project. Did you configure the nuget correctly?

**Comment by sbeidas** [comment]
This issue has been fixed, happy to re-open if someone is still experiencing issues.
