### ISSUE TITLE
Unable to Register Webhook Callback

### ISSUE THREAD

**Issue by Cassidie** [goshippo/shippo-csharp-client#35]
I see you guys provide a way to register a tracking webhook that takes the carrier and tracking number. However, I don't see a way to register the webhook callback url and event type. Is this something that is only available through the Shippo Dashboard, or did I miss some code somewhere that will do this through an api call?

**Comment by mootrichard** [comment]
Yes, the only way to add a webhook URL is through the Shippo dashboard. You can go to [https://app.goshippo.com/api](https://app.goshippo.com/api) to create/register your webhook URL.

**Comment by Cassidie** [comment]
Ok thanks for your quick response! I was hoping it was just missed in this project. lol Oh well.

**Comment by mootrichard** [comment]
No worries! I will keep pushing for API webhook registration because I _too_ wish that we offered this capability.
