### ISSUE TITLE
Missing PRE_TRANSIT on ShippoEnums.TrackingStatus

### ISSUE THREAD

**Issue by vancore295** [goshippo/shippo-csharp-client#46]
PRE_TRANSIT not being on the ShippoEnums.TrackingStatus causes the Newtonsoft Json serializer to crash

could be fixed by https://github.com/goshippo/shippo-csharp-client/pull/45

**Comment by ssong-shippo** [comment]
Hi vancore295, apologies for the delay in reaching out. This should be fixed from v2.1.14 onward. Thanks for reporting.
